apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:                     
  name: todoapp  # Name of the kubernetes resource
spec: 
  type: LoadBalancer             # The service will be exposed by opening a Port on each node and proxying it. 
  selector:
    app: server
    tier: todoapp
    track: stable   # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - protocol: TCP
    port: 5000
    targetPort: http