version: '3'
services:
      
     
  
  app:
    build: ./
    ports:
      - "5000:5000"

  ui:
    build: ./templates
    container_name: todoappui
    ports: 
      - 8081:80
    depends_on:
    - app